train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: E:\dic\Speckle\Speckle_train_HR_400
      repeat: 20
      cache: none
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 4

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: E:\dic\Speckle\Speckle_valid_HR_200
      first_k: 10
      repeat: 160
      cache: none
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      sample_q: 2304
  batch_size: 4

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: sliif
  args:
    encoder_spec:
      name: muse
      args:
        endoder:
          name: rdn
          args:
            no_upsampling: true
            n_colors: 64
    imnet_spec:
      name: resmlps
      args:
        out_dim: 3
        hidden_list: [256, 256, 256, 256]
        coord_hidden_list: [16, 16, 16, 16]

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 100
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 10
